server:
  port: 8080
spring:
  application:
    name: spring-boot-jpa
  jpa:
    database: mysql
    show-sql: false
    generate-ddl: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      #创建表
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/test1?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 10
      idle-timeout: 6000000
      connection-timeout: 30000
      max-lifetime: 180000
  mail:
    host: smtp.qq.com
    username: 2641013950@qq.com
    password: hwgsbdgobwwzecbd
    default-encoding: UTF-8
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true