server:
  port: 8080
spring:
  application:
    name: spring-boot-jpa
  jpa:
    database: mysql
    show-sql: false
    generate-ddl: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      #创建表
      ddl-auto: update
    # 批量插入
    properties:
      jdbc:
        batch_size: 500
        batch_versioned_data: true
        order_inserts: true
        order_updates: true
  datasource:
    url: jdbc:mysql://localhost:3306/test1?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: ENC(b5bhJDtSf/ovJmFQ5ZvU5w==)
    password: ENC(b5bhJDtSf/ovJmFQ5ZvU5w==)
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 10
      idle-timeout: 6000000
      connection-timeout: 30000
      max-lifetime: 180000
  mail:
    host: smtp.qq.com
    username: 2641013950@qq.com
    password: hwgsbdgobwwzecbd
    default-encoding: UTF-8
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

# 设置单个文件大小，单次请求文件的总大小
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
#jasypt:
#  encryptor:
#    password: 123456

#encryptor:
#  property: ENC(b5bhJDtSf/ovJmFQ5ZvU5w==)



  jetcache:
    statIntervalMinutes: 15
    areaInCacheName: false
    local:
      default:
        type: linkedhashmap
        keyConvertor: fastjson
        limit: 100
    remote:
      default:
        type: redis
        keyConvertor: fastjson
        valueEncoder: java
        valueDecoder: java
        poolConfig:
          minIdle: 5
          maxIdle: 20
          maxTotal: 50
        host: ${redis.host}
        port: ${redis.port}


