server:
  port: 8080
spring:
  application:
    name: spring-boot-jpa
  jpa:
    database: mysql
    show-sql: true
    generate-ddl: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      #创建表
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/test?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      auto-commit: true
      minimum-idle: 2
      idle-timeout: 60000
      connection-timeout: 30000
      max-lifetime: 1800000
      pool-name: MyHikariCP
      maximum-pool-size: 15


#server:
#  port: 8080
##日志配置
##logging:
##  config: classpath:logback-config.xml
#
##单数据源配置
#spring:
#  jackson:
#    date-format: yyyy-MM-dd HH:mm:ss
#    time-zone: GMT-8
#  datasource:
#    url: jdbc:mysql://localhost:3306/test?useUnide=true&characterEncoding=UTF-8&useSSL=false&autoReconnect=true
#    username: root
#    password: root
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    hikari:
#      max-lifetime: 30000
#      minimum-idle: 1
#      maximum-pool-size: 20
#      auto-commit: true
#      idle-timeout: 10000
#      connection-timeout: 30000
#    type: com.zaxxer.hikari.HikariDataSource
#  jpa:
#    hibernate:
#      ddl-auto: update
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
#    show-sql: true